example/package.json, example/server.ts, package-lock.json, package.json, src/index.ts, src/plugin.ts, src/server.ts, tsconfig.json
=> feat: add fastify plugin

src/server.ts
=> fix: set headers on raw response

.github/workflows/release.yml, .github/workflows/test.yml
=> chore: set up automated publishing

example/app/routes/index.tsx, example/server.js
`getLoaderContext` was already implemented in the `server.ts`. I just added it to `plugin.ts`, added a test, and also implemented it in the example.
=> Add `getLoaderContext` function parameter to enable adding context to remix loader

example/app/routes/index.tsx, example/app/routes/page-2.tsx, packages/remix-fastify/__tests__/index.test.ts, packages/remix-fastify/src/server.ts
=> feat: use `writeReadableStreamToWritable` properly

.changeset/selfish-cobras-speak.md, example/app/entry.server.tsx, example/app/routes/__layout/index.tsx, example/server.js, packages/remix-fastify/src/plugin.ts, packages/remix-fastify/src/server.ts
=> feat(plugin): allow disabling purging of require cache 

.changeset/rare-hairs-sin.md, example/.env, example/package.json, packages/remix-fastify/src/plugin.ts, packages/remix-fastify/src/utils.ts, pnpm-lock.yaml
closes #75 
working on integration tests, hopefully can get those in a PR soon so this doesn't happen again
=> fix: better windows file path support

.github/workflows/cleanup-cache.yml, .github/workflows/test.yml
=> chore: clean up cache for prs

example/package.json, example/server.js, pnpm-lock.yaml
=> chore(example): updates

.changeset/silent-timers-reply.md, packages/remix-fastify/src/server.ts, packages/remix-fastify/src/static-file-plugin.ts
=> fix: actually determind requested file

example/server.js, packages/remix-fastify/README.md, playground/app/routes/_layout._index.tsx, playground/server.js
same fix as https://github.com/remix-run/remix/pull/7544
=> chore(example): use reloaded build on request

example/package.json, playground/package.json
=> chore(example): watch and restart server when server.js changes

examples/basic/package.json, pnpm-lock.yaml
`@remix-run/serve` isn't used anywhere.
=> fix: remove unused dependency `@remix-run/serve`

examples/basic/package.json, examples/basic/tsconfig.json, examples/playground/app/entry.client.tsx, examples/playground/package.json, examples/playground/tsconfig.json, examples/unstable-vite/app/entry.client.tsx, examples/unstable-vite/package.json, examples/unstable-vite/tsconfig.json, package.json, packages/remix-fastify/package.json, packages/remix-fastify/tsconfig.json, pnpm-lock.yaml, prettier.config.js, scripts/tsconfig.json
=> chore(deps): bump to latest

examples/basic/server.js, examples/playground/server.js, examples/unstable-vite/server.js, pnpm-lock.yaml, scripts/version.js
=> chore: use native esm dirname

examples/basic/server.js, examples/playground/server.js, examples/unstable-vite/server.js, packages/remix-fastify/src/server.ts, pnpm-lock.yaml
=> example: add comment about why addContentTypeParser is needed

examples/basic/server.js, examples/playground/server.js, examples/unstable-vite/server.js
import.meta.dirname was added in node v21.2.0
=> revert: chore: use native esm dirname (#259)

examples/vite/app/root.tsx, examples/vite/env.d.ts, examples/vite/package.json, examples/vite/server.js, examples/vite/tsconfig.json
=> chore: vite template updates

.github/workflows/test.yml, .gitignore, package.json, packages/remix-fastify/package.json, pnpm-lock.yaml
=> chore: check types

.changeset/cold-turtles-press.md, .changeset/fifty-lemons-knock.md, examples/basic/package.json, examples/basic/server.js, packages/remix-fastify/package.json, packages/remix-fastify/src/plugin.ts, pnpm-lock.yaml
the previous way was working..
=> feat: fix and allow configuring cache control

.changeset/pre.json, .pnpmfile.cjs, examples/basic/package.json, examples/playground/package.json, examples/vite/package.json, packages/remix-fastify/CHANGELOG.md, packages/remix-fastify/package.json, pnpm-lock.yaml, scripts/post-changeset.js
=> chore: Update version for release

examples/basic/server.js
=> fix(examples/basic): update static file serving

packages/remix-fastify/README.md
I've updated lots of apps to remix-fastify and always have to remember how so I added the steps to the readme.
=> Add steps to migrate existing app to remix-fastify

.github/workflows/release-pr.yml, package.json, pnpm-lock.yaml
=> ci: publish PRs with pkg-pr-new

.changeset/little-zebras-admire.md, packages/remix-fastify/src/server.ts
=> fix: update url generation for fastify v5

packages/remix-fastify/README.md
=> docs(readme): add a link to a boilerplate project

.github/workflows/test.yml
This reverts commit 24e29ec7c7f73090fe5eac5db0459ab59d94350f.
=> Revert "ci: install latest corepack"

.changeset/stale-berries-sip.md, packages/remix-fastify/src/shared.ts
=> fix: rethrow error after destroying stream

.changeset/tame-cars-burn.md, packages/remix-fastify/package.json, packages/remix-fastify/remix.cjs, packages/remix-fastify/remix.d.cts, packages/remix-fastify/remix.d.ts, packages/remix-fastify/remix.js, packages/remix-fastify/tsdown.config.ts
=> chore: point "." export to "./dist/remix"
