mcansh/remix-fastify

tsconfig.json
Currently types are emited into `dist/src`
=> fix: emit declaration files to dist

src/plugin.ts
The cache header values are currently passed as seconds instead of ms, which the library that `@fastify/static` uses expects (https://www.npmjs.com/package/send#maxage).
You can pass a string value which is correctly parsed in the the right amount of ms.
There's another issue I've noticed, the `assetsBuildDirectory` files do not get handled by the stricter handler (with immutable).
I've tried to set the prefix to `/build/` so they're correctly picked up, but I receive errors for double registration of routes then.
Unsure how to properly resolve that issue.
=> bug: Set the correct cache headers for static files

LICENSE, package-lock.json, package.json
Add `LICENSE` file and add `license` key in package.json file.
Some tools at many companies won't allow you to install packages if they don't specify a license type
=> add MIT license

packages/remix-fastify/__tests__/index.test.ts, packages/remix-fastify/src/server.ts
@see: https://github.com/remix-run/remix/pull/5336
=> fix: request creation when double slashes exist

.changeset/clever-shoes-punch.md, packages/remix-fastify/src/plugin.ts, packages/remix-fastify/src/utils.ts
This PR enables you to use this plugin when running fastify from a different directory to the remix root.
* updates `remixFastify` plugin to take `rootDir` as an option, for if remix root is different to `process.cwd()`
* passes `rootDir` to `glob.sync` as `cwd` option
=> feat: make remix root directory configurable

.changeset/gorgeous-carpets-crash.md, example/package.json, example/remix.config.js, packages/remix-fastify/src/plugin.ts, pnpm-lock.yaml
This fixes an issue that I observed while trying out the HMR prerelease build of Remix.
When Remix makes the HMR request, it adds a `?t=123` parameter to the URL for cache busting. The fastify adapter however did not properly resolve these static assets because it was comparing url (e.g. `build/routes/foo.js?t=123`) with the filename using string equality.
This fixes the issue by parsing the URL and comparing the pathname instead.
To make the example run locally, I also had to upgrade to Remix 1.13.0 (1.12.0 had some issues loading the flat routes properly, somehow it was looking for them in `/outes` instead `/routes` 😅 ). I included this as a separate commit in this PR but I’m happy to remove it.
It doesn't seem like there's a setup for testing the full fastify plugin end-to-end so I …
=> fix: match static files in dev based on the pathname to fix HMR

packages/remix-fastify/src/server.ts
Enabling `@fastify/compress` causes responsed to be prematurely closed. e.g.
```ts
await app.register(import("@fastify/compress"), { global: true })
```
This seems related to this fastify v4 migration point: https://www.fastify.io/docs/latest/Guides/Migration-Guide-V4/#need-to-return-reply-to-signal-a-fork-of-the-promise-chain
(This is the first time I'm using fastify though)
closes #99
=> fix: return reply from response handler

example/package.json, example/scripts/preinstall.mjs
this way you don't need to opt out of installing dependencies when using `create-remix`
=> chore: add preinstall script to example

.changeset/some-unique-id.md, packages/remix-fastify/src/utils.ts
Currently, `filePublicPath` is calculated off of the unnormalized version of the path, so "public/" doesn't match anything on Windows systems.  This leads to `reply.sendFile` trying to read from a file that likely does not exist, since it tries to use `path.join(process.cwd(), "public")` as the root.
=> fix: use normalized path for static files.

.changeset/six-lizards-float.md, example/package.json, packages/remix-fastify/src/static-file-plugin.ts, packages/remix-fastify/src/utils.ts, playground/app/routes/_layout._index.tsx, playground/package.json, playground/server.js
move glob inside onRequest hook in order for getStaticFiles to be called. doing this allows the removal of `node --watch` which i totally didn't realize was restarting the server as we import the build 😅
=> fix: make this work without node --watch

examples/unstable-vite/server.js
follow up to #222 
closes #226
=> fix(examples/vite): use static module id as the variable isn’t exported anymore

.changeset/gentle-dingos-sit.md, package.json, packages/remix-fastify/src/server.ts
previously using `fastify({ http2: true })` resulted in type errors for the handler when passing the request
this has been fixed by passing the server type to all uses of the request and reply internally
the changes in this PR also give us `https` support as we allow any of `http.Server | https.Server | http2.Http2Server | http2.Http2SecureServer;` to be used as far as types go.
=> feat: allow http2/https servers

examples/basic/server.js, examples/playground/app/routes/_layout._index.tsx, examples/playground/server.js, examples/unstable-vite/server.js
closes #244
suggestion found by @⁠adaboese [fastify/fastify#5306 (comment)](https⁠://github.com/fastify/fastify/discussions/5306#discussioncomment-8399986)
=> examples: encapsulate catch all route for remix to allow for other routes content parsers

examples/vite/server.js
vite will serve everything from its middlewares so registering any of the instances of `@fastify/static` are unnecessary
closes #288 
=> chore(example): dont register `@fastify/static` in development

.changeset/tender-bananas-promise.md, packages/remix-fastify/src/plugin.ts
We have a use case where we would like to customize parameters like `decorateReply` or `setHeaders` in the `@fastify/static` plugin.
This PR accepts and forwards or overrides options to the plugin. This can be useful if you want to disable the `decorateReply` parameter, set more custom headers, or set other stuff.
Example use case:
```ts
const app = fastify();
// Let's say you have already registered the same `@fastify/static` plugin in your app.
app.register(fastifyStatic, { /* ... */ });
app.register(remixFastify, {
fastifyStaticOptions: {
decorateReply: false  // Then this parameter is needed, otherwise it will throw an error from Fastify
}
});
```
=> feat: accept fastify/static plugin options

.changeset/tender-plums-taste.md, packages/remix-fastify/src/plugin.ts, packages/remix-fastify/src/server.ts
This PR allows you to pass a custom production server build to the request handler. In some situations, you might want to load the server build using a different approach. (for example, use `require` instead of `import` or pass the object from the memory)
We need this because our runtime setup prevents us from using the default dynamic import approach. We would like to have an option that allows us to manually pass the server build without basically building the same `remix-fastify` plugin with the helper functions provided.
This parameter is better suited to advanced users, while the default dynamic import approach should be sufficient for normal users.
=> feat: accept custom production server build

examples/basic/package.json, examples/basic/server.js, examples/playground/package.json, examples/playground/server.js, examples/vite/package.json, examples/vite/server/index.ts, package.json, pnpm-lock.yaml
=> chore: use chalk for node <= 20 support

.changeset/cyan-suits-kneel.md, packages/remix-fastify/src/plugin.ts
Hey when I use the basename in remix vite plugin and set base in vite locally assets are served at the same basename. But when using your plugin assets are still served at the root in production mode. So just made the change to respect the basename path.
If you want something that is more flexible let me know.
```
export default defineConfig({
base: "/platform/",
plugins: [
remix({
basename: "/platform/",
}),
],
})
```
=> fix asset serving when using a basename

.changeset/bright-pigs-promise.md, examples/basic/server.js, packages/remix-fastify/src/plugin.ts
It turns out that if you set "cacheControl: true" in the options to @fastify/static, it overrides the headers you set in the setHeaders callback.  This bug was introduced to remix-fastify in April 2024 in this commit:
https://github.com/mcansh/remix-fastify/commit/a7fcb6da513ce17ac106f0930373f3edd9d976c9
I identified the issue as I thought it was a bug with @fastify/static, which was discussed here: https://github.com/fastify/fastify-static/issues/477, but it was actually a bug with remix-fastify.
I will admit that the @fastify/static options are very unclear and not user friendly.
=> fix(plugin): we're handling cache-control

.changeset/stupid-onions-float.md, packages/remix-fastify/src/plugins/index.ts
Previously, the server build was loaded lazily within the request handler in the Fastify plugin. This PR modifies the plugin to import and load the server build during plugin registration itself.
This change ensures the server build is ready when the first request arrives, eliminating the import cost and reducing latency for the initial user experience.
=> Eagerly load server build in Fastify plugin

.changeset/wild-bobcats-do.md, examples/playground/server.js, package.json, packages/remix-fastify/package.json, packages/remix-fastify/src/shared.ts, pnpm-lock.yaml
fixes #491
Co-Authored-By: wong2 <wonderfuly@gmail.com>
=> fix: destroy stream on error
